version: '3'


services:

  mongodb:
    image: mongo:latest
    container_name: auth_mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root,
  # redis:
  #   container_name: "redis_db"
  #   image: redis:alpine
  #   command: redis-server --requirepass lakedy
  #   ports:
  #     - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    ports:
      - 9200:9200
      - 9300:9300

    environment:
      discovery.type: single-node
